import { useState } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { FileText, Download, Users, BarChart3, UserCheck, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { drawBarChart, drawPieChart, drawStackedBar, DEFAULT_COLORS } from './pdfCharts';

interface StudentMarkData {
  student_usn: string;
  subject_id: string;
  internal_marks: number;
  external_marks: number;
  grade: string | null;
  subjects?: { id: string; name: string; max_internal: number; max_external: number } | null;
}

interface AttendanceSummary {
  usn: string;
  totalClasses: number;
  present: number;
  absent: number;
  percentage: number;
}

interface ReportGeneratorProps {
  studentMarks: StudentMarkData[];
  attendanceSummaries: AttendanceSummary[];
  professorName: string;
}

const gradeToGP = (grade: string | null): number => {
  const map: Record<string, number> = { 'O': 10, 'A+': 9, 'A': 8, 'B+': 7, 'B': 6, 'C': 5, 'P': 4, 'F': 0 };
  return map[grade || ''] ?? 0;
};

export const ReportGenerator = ({ studentMarks, attendanceSummaries, professorName }: ReportGeneratorProps) => {
  const [reportType, setReportType] = useState('class-performance');
  const [generating, setGenerating] = useState(false);

  const studentGroups = studentMarks.reduce<Record<string, StudentMarkData[]>>((acc, mark) => {
    if (!acc[mark.student_usn]) acc[mark.student_usn] = [];
    acc[mark.student_usn].push(mark);
    return acc;
  }, {});

  const studentSummaries = Object.entries(studentGroups).map(([usn, marks]) => {
    const totalGP = marks.reduce((sum, m) => sum + gradeToGP(m.grade), 0);
    const sgpa = marks.length > 0 ? totalGP / marks.length : 0;
    const totalInternal = marks.reduce((sum, m) => sum + m.internal_marks, 0);
    const totalExternal = marks.reduce((sum, m) => sum + m.external_marks, 0);
    return { usn, marks, sgpa, totalInternal, totalExternal };
  }).sort((a, b) => b.sgpa - a.sgpa);

  const addHeader = (doc: jsPDF, title: string) => {
    doc.setFillColor(14, 116, 144);
    doc.rect(0, 0, doc.internal.pageSize.getWidth(), 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('EDU-PREDICT', 14, 18);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(title, 14, 30);
    doc.setFontSize(9);
    doc.text(`Generated by: ${professorName}  |  Date: ${new Date().toLocaleDateString()}`, 14, 37);
    doc.setTextColor(0, 0, 0);
  };

  const addFooter = (doc: jsPDF) => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(
        `Page ${i} of ${pageCount}  |  EDU-PREDICT Academic Report`,
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }
  };

  const generateClassPerformanceReport = () => {
    const doc = new jsPDF();
    addHeader(doc, 'Class Performance Report');

    // Summary stats
    const avgSGPA = studentSummaries.length > 0
      ? (studentSummaries.reduce((s, st) => s + st.sgpa, 0) / studentSummaries.length).toFixed(2)
      : '0.00';
    const highPerformers = studentSummaries.filter(s => s.sgpa >= 8).length;
    const atRisk = studentSummaries.filter(s => s.sgpa < 4).length;
    const average = studentSummaries.filter(s => s.sgpa >= 4 && s.sgpa < 6).length;
    const good = studentSummaries.filter(s => s.sgpa >= 6 && s.sgpa < 8).length;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 14, 52);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Students: ${studentSummaries.length}`, 14, 60);
    doc.text(`Average SGPA: ${avgSGPA}`, 14, 66);
    doc.text(`High Performers (SGPA ≥ 8): ${highPerformers}`, 14, 72);
    doc.text(`At-Risk Students (SGPA < 4): ${atRisk}`, 14, 78);

    // --- PIE CHART: Student Performance Distribution ---
    drawPieChart(doc, [
      { label: 'Excellent (≥8)', value: highPerformers, color: [16, 185, 129] },
      { label: 'Good (6-8)', value: good, color: [59, 130, 246] },
      { label: 'Average (4-6)', value: average, color: [245, 158, 11] },
      { label: 'At Risk (<4)', value: atRisk, color: [239, 68, 68] },
    ], 155, 66, 22, 'Performance Distribution');

    // --- BAR CHART: SGPA Distribution ---
    const ranges = ['0-2', '2-4', '4-6', '6-8', '8-10'];
    const counts = ranges.map((r) => {
      const [min, max] = r.split('-').map(Number);
      return studentSummaries.filter(s => s.sgpa >= min && s.sgpa < (max === 10 ? 11 : max)).length;
    });

    drawBarChart(doc, ranges.map((r, i) => ({
      label: r,
      value: counts[i],
      color: DEFAULT_COLORS[i % DEFAULT_COLORS.length],
    })), 14, 88, 180, 60, 'SGPA Distribution');

    // Student ranking table
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Student Rankings', 14, 162);

    autoTable(doc, {
      startY: 166,
      head: [['Rank', 'USN', 'Subjects', 'Internal', 'External', 'SGPA', 'Status']],
      body: studentSummaries.map((s, i) => [
        i + 1, s.usn, s.marks.length, s.totalInternal, s.totalExternal,
        s.sgpa.toFixed(2),
        s.sgpa >= 8 ? 'Excellent' : s.sgpa >= 6 ? 'Good' : s.sgpa >= 4 ? 'Average' : 'At Risk',
      ]),
      theme: 'grid',
      headStyles: { fillColor: [14, 116, 144], textColor: 255 },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      styles: { fontSize: 9 },
    });

    addFooter(doc);
    doc.save('class-performance-report.pdf');
  };

  const generateStudentDetailReport = () => {
    const doc = new jsPDF();
    addHeader(doc, 'Detailed Student Marks Report');

    // --- BAR CHART: Top 10 students by SGPA ---
    const top10 = studentSummaries.slice(0, 10);
    if (top10.length > 0) {
      drawBarChart(doc, top10.map((s) => ({
        label: s.usn.slice(-5),
        value: parseFloat(s.sgpa.toFixed(1)),
        color: s.sgpa >= 8 ? [16, 185, 129] : s.sgpa >= 6 ? [59, 130, 246] : s.sgpa >= 4 ? [245, 158, 11] : [239, 68, 68],
      })), 14, 46, 180, 65, 'Top Students by SGPA');
    }

    let yPos = 120;

    studentSummaries.forEach((student, idx) => {
      if (yPos > 240) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`${idx + 1}. ${student.usn}  —  SGPA: ${student.sgpa.toFixed(2)}`, 14, yPos);
      yPos += 4;

      autoTable(doc, {
        startY: yPos,
        head: [['Subject', 'Internal', 'External', 'Total', 'Grade', 'GP']],
        body: student.marks.map(m => [
          m.subjects?.name || 'Unknown',
          `${m.internal_marks}/${m.subjects?.max_internal || 50}`,
          `${m.external_marks}/${m.subjects?.max_external || 100}`,
          m.internal_marks + m.external_marks,
          m.grade || '-',
          gradeToGP(m.grade),
        ]),
        theme: 'striped',
        headStyles: { fillColor: [14, 116, 144], textColor: 255 },
        styles: { fontSize: 8 },
        margin: { left: 14 },
      });

      yPos = ((doc as any).lastAutoTable?.finalY || yPos) + 12;
    });

    addFooter(doc);
    doc.save('student-marks-detail-report.pdf');
  };

  const generateAttendanceReport = () => {
    const doc = new jsPDF();
    addHeader(doc, 'Attendance Report');

    const totalStudents = attendanceSummaries.length;
    const avgAttendance = totalStudents > 0
      ? (attendanceSummaries.reduce((s, a) => s + a.percentage, 0) / totalStudents).toFixed(1)
      : '0';
    const lowAttendance = attendanceSummaries.filter(a => a.percentage < 75).length;
    const goodAttendance = attendanceSummaries.filter(a => a.percentage >= 75).length;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Attendance Summary', 14, 52);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Students: ${totalStudents}`, 14, 60);
    doc.text(`Average Attendance: ${avgAttendance}%`, 14, 66);
    doc.text(`Students Below 75%: ${lowAttendance}`, 14, 72);

    // --- PIE CHART: Attendance status distribution ---
    const critical = attendanceSummaries.filter(a => a.percentage < 50).length;
    const warning = attendanceSummaries.filter(a => a.percentage >= 50 && a.percentage < 75).length;

    drawPieChart(doc, [
      { label: 'OK (≥75%)', value: goodAttendance, color: [16, 185, 129] },
      { label: 'Warning (50-75%)', value: warning, color: [245, 158, 11] },
      { label: 'Critical (<50%)', value: critical, color: [239, 68, 68] },
    ], 155, 66, 22, 'Attendance Status');

    // --- BAR CHART: Bottom 10 attendance ---
    const bottom10 = [...attendanceSummaries].sort((a, b) => a.percentage - b.percentage).slice(0, 10);
    if (bottom10.length > 0) {
      drawBarChart(doc, bottom10.map((a) => ({
        label: a.usn.slice(-5),
        value: a.percentage,
        color: a.percentage >= 75 ? [16, 185, 129] : a.percentage >= 50 ? [245, 158, 11] : [239, 68, 68],
      })), 14, 88, 180, 60, 'Lowest Attendance Students (%)');
    }

    // --- STACKED BAR: Overall present/absent ---
    const totalPresent = attendanceSummaries.reduce((s, a) => s + a.present, 0);
    const totalAbsent = attendanceSummaries.reduce((s, a) => s + a.absent, 0);
    drawStackedBar(doc, 14, 160, 180, 10, [
      { value: totalPresent, color: [16, 185, 129], label: 'Present' },
      { value: totalAbsent, color: [239, 68, 68], label: 'Absent' },
    ], 'Overall Attendance Ratio');

    // Table
    autoTable(doc, {
      startY: 186,
      head: [['USN', 'Total Classes', 'Present', 'Absent', 'Percentage', 'Status']],
      body: attendanceSummaries
        .sort((a, b) => a.percentage - b.percentage)
        .map(a => [
          a.usn, a.totalClasses, a.present, a.absent, `${a.percentage}%`,
          a.percentage >= 75 ? 'OK' : a.percentage >= 50 ? 'Warning' : 'Critical',
        ]),
      theme: 'grid',
      headStyles: { fillColor: [14, 116, 144], textColor: 255 },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      styles: { fontSize: 9 },
      didParseCell: (data: any) => {
        if (data.column.index === 5 && data.section === 'body') {
          const val = data.cell.raw as string;
          if (val === 'Critical') data.cell.styles.textColor = [220, 38, 38];
          else if (val === 'Warning') data.cell.styles.textColor = [202, 138, 4];
          else data.cell.styles.textColor = [22, 163, 74];
        }
      },
    });

    addFooter(doc);
    doc.save('attendance-report.pdf');
  };

  const generateComprehensiveReport = () => {
    const doc = new jsPDF();

    // Page 1: Class Performance
    addHeader(doc, 'Comprehensive Academic Report');

    const avgSGPA = studentSummaries.length > 0
      ? (studentSummaries.reduce((s, st) => s + st.sgpa, 0) / studentSummaries.length).toFixed(2)
      : '0.00';
    const highPerformers = studentSummaries.filter(s => s.sgpa >= 8).length;
    const atRisk = studentSummaries.filter(s => s.sgpa < 4).length;
    const good = studentSummaries.filter(s => s.sgpa >= 6 && s.sgpa < 8).length;
    const average = studentSummaries.filter(s => s.sgpa >= 4 && s.sgpa < 6).length;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Academic Performance Overview', 14, 52);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Students: ${studentSummaries.length}  |  Average SGPA: ${avgSGPA}`, 14, 60);
    doc.text(`High Performers: ${highPerformers}  |  At Risk: ${atRisk}`, 14, 66);

    // --- PIE CHART ---
    drawPieChart(doc, [
      { label: 'Excellent', value: highPerformers, color: [16, 185, 129] },
      { label: 'Good', value: good, color: [59, 130, 246] },
      { label: 'Average', value: average, color: [245, 158, 11] },
      { label: 'At Risk', value: atRisk, color: [239, 68, 68] },
    ], 155, 60, 18, 'Grade Distribution');

    // --- BAR CHART: Top students ---
    const top8 = studentSummaries.slice(0, 8);
    drawBarChart(doc, top8.map((s) => ({
      label: s.usn.slice(-5),
      value: parseFloat(s.sgpa.toFixed(1)),
    })), 14, 76, 180, 55, 'Top Students SGPA');

    autoTable(doc, {
      startY: 140,
      head: [['Rank', 'USN', 'SGPA', 'Internal', 'External', 'Status']],
      body: studentSummaries.slice(0, 20).map((s, i) => [
        i + 1, s.usn, s.sgpa.toFixed(2), s.totalInternal, s.totalExternal,
        s.sgpa >= 8 ? 'Excellent' : s.sgpa >= 6 ? 'Good' : s.sgpa >= 4 ? 'Average' : 'At Risk',
      ]),
      theme: 'grid',
      headStyles: { fillColor: [14, 116, 144], textColor: 255 },
      styles: { fontSize: 8 },
    });

    // Page 2: Attendance
    if (attendanceSummaries.length > 0) {
      doc.addPage();
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('2. Attendance Overview', 14, 20);

      const avgAtt = (attendanceSummaries.reduce((s, a) => s + a.percentage, 0) / attendanceSummaries.length).toFixed(1);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Average Attendance: ${avgAtt}%  |  Below 75%: ${attendanceSummaries.filter(a => a.percentage < 75).length}`, 14, 28);

      // --- Stacked bar ---
      const totalPresent = attendanceSummaries.reduce((s, a) => s + a.present, 0);
      const totalAbsent = attendanceSummaries.reduce((s, a) => s + a.absent, 0);
      drawStackedBar(doc, 14, 36, 180, 10, [
        { value: totalPresent, color: [16, 185, 129], label: 'Present' },
        { value: totalAbsent, color: [239, 68, 68], label: 'Absent' },
      ], 'Overall Attendance');

      // --- BAR CHART: attendance by student ---
      const bottom8 = [...attendanceSummaries].sort((a, b) => a.percentage - b.percentage).slice(0, 8);
      drawBarChart(doc, bottom8.map((a) => ({
        label: a.usn.slice(-5),
        value: a.percentage,
        color: a.percentage >= 75 ? [16, 185, 129] : a.percentage >= 50 ? [245, 158, 11] : [239, 68, 68],
      })), 14, 58, 180, 55, 'Students with Lowest Attendance (%)');

      autoTable(doc, {
        startY: 120,
        head: [['USN', 'Classes', 'Present', 'Absent', '%', 'Status']],
        body: attendanceSummaries.sort((a, b) => a.percentage - b.percentage).map(a => [
          a.usn, a.totalClasses, a.present, a.absent, `${a.percentage}%`,
          a.percentage >= 75 ? 'OK' : a.percentage >= 50 ? 'Warning' : 'Critical',
        ]),
        theme: 'grid',
        headStyles: { fillColor: [14, 116, 144], textColor: 255 },
        styles: { fontSize: 8 },
      });
    }

    addFooter(doc);
    doc.save('comprehensive-academic-report.pdf');
  };

  const handleGenerate = () => {
    setGenerating(true);
    try {
      switch (reportType) {
        case 'class-performance': generateClassPerformanceReport(); break;
        case 'student-detail': generateStudentDetailReport(); break;
        case 'attendance': generateAttendanceReport(); break;
        case 'comprehensive': generateComprehensiveReport(); break;
      }
      toast.success('Report generated successfully!');
    } catch {
      toast.error('Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const reportTypes = [
    { value: 'class-performance', label: 'Class Performance', icon: BarChart3, description: 'Rankings, SGPA bar chart, pie distribution' },
    { value: 'student-detail', label: 'Detailed Student Marks', icon: Users, description: 'Per-student marks with top SGPA bar chart' },
    { value: 'attendance', label: 'Attendance Report', icon: UserCheck, description: 'Pie chart, bar chart & stacked attendance ratios' },
    { value: 'comprehensive', label: 'Comprehensive Report', icon: FileText, description: 'Full visual report with all charts combined' },
  ];

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2">
        {reportTypes.map((rt) => (
          <button
            key={rt.value}
            onClick={() => setReportType(rt.value)}
            className={`group rounded-xl border p-5 text-left transition-all hover:shadow-sm ${
              reportType === rt.value
                ? 'border-primary bg-primary/5 shadow-sm'
                : 'border-border hover:border-primary/30'
            }`}
          >
            <div className="flex items-center gap-3 mb-2">
              <div className={`flex h-10 w-10 items-center justify-center rounded-lg transition-colors ${
                reportType === rt.value ? 'bg-primary/15' : 'bg-muted/50'
              }`}>
                <rt.icon className={`h-5 w-5 ${reportType === rt.value ? 'text-primary' : 'text-muted-foreground'}`} />
              </div>
              <div>
                <p className="font-semibold text-foreground">{rt.label}</p>
                {reportType === rt.value && (
                  <Badge variant="default" className="text-xs mt-0.5">Selected</Badge>
                )}
              </div>
            </div>
            <p className="text-sm text-muted-foreground">{rt.description}</p>
          </button>
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Download className="h-5 w-5 text-primary" />
            Generate Report
          </CardTitle>
          <CardDescription>
            Selected: {reportTypes.find(r => r.value === reportType)?.label} — {studentSummaries.length} students, {attendanceSummaries.length} attendance records
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Button
            onClick={handleGenerate}
            disabled={generating || (studentMarks.length === 0 && reportType !== 'attendance')}
            className="w-full gap-2 h-11"
          >
            {generating ? (
              <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</>
            ) : (
              <><Download className="h-4 w-4" /> Download PDF Report</>
            )}
          </Button>
          {studentMarks.length === 0 && reportType !== 'attendance' && (
            <p className="mt-3 text-sm text-muted-foreground text-center">No student marks data available to generate this report.</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
};
